name: kinetic_link

packages:
  - apps/*
  - packages/*

scripts:
  test:
    exec: flutter test
    description: Run Flutter tests across packages
    packageFilters:
      dirExists: test
      flutter: true

  test_dart:
    exec: dart test
    description: Run pure Dart package tests
    packageFilters:
      dirExists: test
      flutter: false

  analyze:
    exec: flutter analyze
    description: Analyze Flutter packages
    packageFilters:
      flutter: true

  pub_get:
    exec: flutter pub get
    description: Get pub dependencies for all packages
    packageFilters:
      flutter: true

  build_link:
    exec: flutter build apk --release
    description: Build release APK for Kinetic Link
    packageFilters:
      scope: "link"

  build_kids:
    exec: flutter build apk --release
    description: Build release APK for kids app
    packageFilters:
      scope: "kids"
