import 'package:drift/drift.dart';
import 'package:path_provider/path_provider.dart';

import 'encrypted_open.dart';
import 'tables.dart';

part 'app_database.drift.dart';

@DriftDatabase(
  tables: [
    PersonalLists,
    PersonalTasks,
    PersonalNotes,
    PersonalSubtasks,
    PartnerProposals,
    AppSettings,
    ExclusionRules,
    AiSuggestions,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  /// Internal constructor for testing with a custom executor.
  AppDatabase.withExecutor(super.executor);

  @override
  int get schemaVersion => 14;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onUpgrade: (m, from, to) async {
      if (from < 2) {
        await m.addColumn(personalTasks, personalTasks.remindAt);
      }
      if (from < 3) {
        await m.addColumn(personalTasks, personalTasks.webdavEtag);
        await m.addColumn(personalTasks, personalTasks.syncState);
        await m.createTable(personalNotes);
      }
      if (from < 4) {
        await m.createTable(appSettings);
      }
      if (from < 5) {
        await m.addColumn(partnerProposals, partnerProposals.autoGenerated);
        await m.createTable(exclusionRules);
      }
      if (from < 6) {
        await m.addColumn(partnerProposals, partnerProposals.syncState);
      }
      if (from < 7) {
        await m.addColumn(personalTasks, personalTasks.customCategory);
        await m.addColumn(personalNotes, personalNotes.category);
        await m.addColumn(personalNotes, personalNotes.sortOrder);
      }
      if (from < 8) {
        await customStatement(
          'ALTER TABLE app_settings ADD COLUMN task_category_order TEXT',
        );
        await customStatement(
          'ALTER TABLE app_settings ADD COLUMN note_category_order TEXT',
        );
      }
      if (from < 9) {
        await m.addColumn(personalTasks, personalTasks.targetKidId);
      }
      if (from < 10) {
        await m.addColumn(personalTasks, personalTasks.xpReward);
      }
      if (from < 11) {
        await customStatement(
          'ALTER TABLE app_settings ADD COLUMN last_suggestion_run_at INTEGER',
        );
        await customStatement(
          'ALTER TABLE app_settings ADD COLUMN last_partner_suggestion_run_at INTEGER',
        );
        await m.createTable(aiSuggestions);
      }
      if (from < 12) {
        await m.addColumn(aiSuggestions, aiSuggestions.explanation);
      }
      if (from < 13) {
        await m.addColumn(appSettings, appSettings.localeCode);
      }
      if (from < 14) {
        await m.addColumn(aiSuggestions, aiSuggestions.dedupeKey);
        await m.addColumn(aiSuggestions, aiSuggestions.relatedTaskIds);
      }
    },
  );

  /// Encrypted on-disk SQLite (SQLite3MultipleCiphers) in documents.
  static QueryExecutor _openConnection() {
    return openEncryptedDatabase(
      name: 'kinetic_parent',
      databaseDirectory: getApplicationDocumentsDirectory,
    );
  }
}
