import '../../../todo/models/enums.dart';

/// PartnerProposal — a task proposed by another link member in the family.
///
/// Proposals represent inter-link communication: one link member suggests a task
/// for another link member's queue. Status tracks acceptance workflow.
class PartnerProposal {
  final String id;
  final String fromLinkId;

  /// Target link member id; null means any other member (legacy / broadcast).
  final String? toMemberId;
  final String taskTitle;
  final String? taskNotes;
  final String taskCategory;
  final TaskPriority taskPriority;
  final DateTime? taskDueDate;
  final ProposalStatus status;
  final DateTime receivedAt;
  final DateTime updatedAt;

  /// true = generated automatically by the local proposal engine.
  final bool autoGenerated;

  const PartnerProposal({
    required this.id,
    required this.fromLinkId,
    this.toMemberId,
    required this.taskTitle,
    this.taskNotes,
    this.taskCategory = 'other',
    required this.taskPriority,
    this.taskDueDate,
    required this.status,
    required this.receivedAt,
    required this.updatedAt,
    this.autoGenerated = false,
  });

  /// Change proposal status (e.g., pending → accepted).
  PartnerProposal copyWithStatus(ProposalStatus newStatus) {
    return PartnerProposal(
      id: id,
      fromLinkId: fromLinkId,
      toMemberId: toMemberId,
      taskTitle: taskTitle,
      taskNotes: taskNotes,
      taskCategory: taskCategory,
      taskPriority: taskPriority,
      taskDueDate: taskDueDate,
      status: newStatus,
      receivedAt: receivedAt,
      updatedAt: DateTime.now().toUtc(),
      autoGenerated: autoGenerated,
    );
  }

  /// Whether this proposal should appear in [myLinkId]'s inbox.
  bool isAddressedTo(String myLinkId) {
    if (fromLinkId == myLinkId) return false;
    if (toMemberId == null || toMemberId!.isEmpty) return true;
    return toMemberId == myLinkId;
  }

  @override
  String toString() =>
      'PartnerProposal(id: $id, title: $taskTitle, status: $status, '
      'to: $toMemberId, priority: $taskPriority, autoGenerated: $autoGenerated)';
}
