import '../../../todo/models/enums.dart';

/// LinkMemberProposal — a task proposed by another link member in the family.
///
/// Proposals represent inter-link communication: one link member suggests a task
/// for another link member's queue. Status tracks acceptance workflow.
class LinkMemberProposal {
  final String id;
  final String fromLinkId;

  /// Target link member id; null means any other member (legacy / broadcast).
  final String? toMemberId;
  final String taskTitle;
  final String? taskNotes;
  final String taskCategory;
  final TaskPriority taskPriority;
  final DateTime? taskDueDate;
  final ProposalStatus status;
  final DateTime receivedAt;
  final DateTime updatedAt;

  /// true = generated automatically by the local proposal engine.
  final bool autoGenerated;

  /// Sender's personal task id when this proposal was created.
  final String? sourceTaskId;

  /// Receiver's personal task id created when this proposal was accepted.
  final String? resultTaskId;

  const LinkMemberProposal({
    required this.id,
    required this.fromLinkId,
    this.toMemberId,
    required this.taskTitle,
    this.taskNotes,
    this.taskCategory = 'other',
    required this.taskPriority,
    this.taskDueDate,
    required this.status,
    required this.receivedAt,
    required this.updatedAt,
    this.autoGenerated = false,
    this.sourceTaskId,
    this.resultTaskId,
  });

  /// Change proposal status (e.g., pending → accepted).
  LinkMemberProposal copyWithStatus(ProposalStatus newStatus) {
    return copyWith(status: newStatus, updatedAt: DateTime.now().toUtc());
  }

  LinkMemberProposal copyWith({
    String? id,
    String? fromLinkId,
    String? toMemberId,
    String? taskTitle,
    String? taskNotes,
    String? taskCategory,
    TaskPriority? taskPriority,
    DateTime? taskDueDate,
    ProposalStatus? status,
    DateTime? receivedAt,
    DateTime? updatedAt,
    bool? autoGenerated,
    String? sourceTaskId,
    String? resultTaskId,
  }) {
    return LinkMemberProposal(
      id: id ?? this.id,
      fromLinkId: fromLinkId ?? this.fromLinkId,
      toMemberId: toMemberId ?? this.toMemberId,
      taskTitle: taskTitle ?? this.taskTitle,
      taskNotes: taskNotes ?? this.taskNotes,
      taskCategory: taskCategory ?? this.taskCategory,
      taskPriority: taskPriority ?? this.taskPriority,
      taskDueDate: taskDueDate ?? this.taskDueDate,
      status: status ?? this.status,
      receivedAt: receivedAt ?? this.receivedAt,
      updatedAt: updatedAt ?? this.updatedAt,
      autoGenerated: autoGenerated ?? this.autoGenerated,
      sourceTaskId: sourceTaskId ?? this.sourceTaskId,
      resultTaskId: resultTaskId ?? this.resultTaskId,
    );
  }

  /// Whether this proposal should appear in [myLinkId]'s inbox.
  bool isAddressedTo(String myLinkId) {
    if (fromLinkId == myLinkId) return false;
    if (toMemberId == null || toMemberId!.isEmpty) return true;
    return toMemberId == myLinkId;
  }

  @override
  String toString() =>
      'LinkMemberProposal(id: $id, title: $taskTitle, status: $status, '
      'to: $toMemberId, priority: $taskPriority, autoGenerated: $autoGenerated)';
}
