import 'package:drift/drift.dart';
import 'package:path_provider/path_provider.dart';

import 'encrypted_open.dart';
import 'tables.dart';

part 'app_database.drift.dart';

@DriftDatabase(
  tables: [
    PersonalLists,
    PersonalTasks,
    PersonalNotes,
    PersonalSubtasks,
    LinkMemberProposals,
    AppSettings,
    ExclusionRules,
    AiSuggestions,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  /// Internal constructor for testing with a custom executor.
  AppDatabase.withExecutor(super.executor);

  @override
  int get schemaVersion => 22;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onUpgrade: (m, from, to) async {
      if (from < 2) {
        await m.addColumn(personalTasks, personalTasks.remindAt);
      }
      if (from < 3) {
        await m.addColumn(personalTasks, personalTasks.webdavEtag);
        await m.addColumn(personalTasks, personalTasks.syncState);
        await m.createTable(personalNotes);
      }
      if (from < 4) {
        await m.createTable(appSettings);
      }
      if (from < 5) {
        await m.addColumn(linkMemberProposals, linkMemberProposals.autoGenerated);
        await m.createTable(exclusionRules);
      }
      if (from < 6) {
        await m.addColumn(linkMemberProposals, linkMemberProposals.syncState);
      }
      if (from < 7) {
        await m.addColumn(personalTasks, personalTasks.customCategory);
        await m.addColumn(personalNotes, personalNotes.category);
        await m.addColumn(personalNotes, personalNotes.sortOrder);
      }
      if (from < 8) {
        await customStatement(
          'ALTER TABLE app_settings ADD COLUMN task_category_order TEXT',
        );
        await customStatement(
          'ALTER TABLE app_settings ADD COLUMN note_category_order TEXT',
        );
      }
      if (from < 9) {
        await m.addColumn(personalTasks, personalTasks.targetKidId);
      }
      if (from < 10) {
        await m.addColumn(personalTasks, personalTasks.xpReward);
      }
      if (from < 11) {
        await customStatement(
          'ALTER TABLE app_settings ADD COLUMN last_suggestion_run_at INTEGER',
        );
        await customStatement(
          'ALTER TABLE app_settings ADD COLUMN last_family_member_suggestion_run_at INTEGER',
        );
        await m.createTable(aiSuggestions);
      }
      if (from < 12) {
        await m.addColumn(aiSuggestions, aiSuggestions.explanation);
      }
      if (from < 13) {
        await m.addColumn(appSettings, appSettings.localeCode);
      }
      if (from < 14) {
        await m.addColumn(aiSuggestions, aiSuggestions.dedupeKey);
        await m.addColumn(aiSuggestions, aiSuggestions.relatedTaskIds);
      }
      if (from < 15) {
        await m.addColumn(personalNotes, personalNotes.deletedAt);
      }
      if (from < 16) {
        await m.addColumn(personalNotes, personalNotes.isContentHidden);
      }
      if (from < 17) {
        await m.addColumn(personalTasks, personalTasks.verifierLinkId);
        await m.addColumn(personalNotes, personalNotes.sharedMemberIds);
        await m.addColumn(linkMemberProposals, linkMemberProposals.toMemberId);
      }
      if (from < 18) {
        // Parent/adult wording dropped in favour of "link".
        await m.renameColumn(
          linkMemberProposals,
          'from_parent_id',
          linkMemberProposals.fromLinkId,
        );
        if (from >= 17) {
          await m.renameColumn(
            personalTasks,
            'verifier_adult_id',
            personalTasks.verifierLinkId,
          );
        }
      }
      if (from < 19) {
        // Idempotent: createTable(personalNotes) on older upgrade paths already
        // materializes the current schema, which includes this column.
        if (!await _columnExists('personal_notes', 'updated_by_link_id')) {
          await m.addColumn(personalNotes, personalNotes.updatedByLinkId);
        }
      }
      if (from < 20) {
        final proposalsTable = await _proposalsTableName();
        if (!await _columnExists(proposalsTable, 'source_task_id')) {
          await m.addColumn(linkMemberProposals, linkMemberProposals.sourceTaskId);
        }
        if (!await _columnExists(proposalsTable, 'result_task_id')) {
          await m.addColumn(linkMemberProposals, linkMemberProposals.resultTaskId);
        }
      }
      if (from < 21) {
        // Rename legacy partner_* identifiers to link_member_* / family_member_*.
        if (await _tableExists('partner_proposals') &&
            !await _tableExists('link_member_proposals')) {
          await customStatement(
            'ALTER TABLE partner_proposals RENAME TO link_member_proposals',
          );
        }
        if (await _columnExists('app_settings', 'last_partner_suggestion_run_at') &&
            !await _columnExists(
              'app_settings',
              'last_family_member_suggestion_run_at',
            )) {
          await customStatement(
            'ALTER TABLE app_settings RENAME COLUMN '
            'last_partner_suggestion_run_at TO last_family_member_suggestion_run_at',
          );
        }
      }
      if (from < 22) {
        await m.addColumn(personalNotes, personalNotes.isLocalOnly);
        await m.addColumn(personalNotes, personalNotes.linkedTaskIds);
      }
    },
  );

  Future<String> _proposalsTableName() async {
    if (await _tableExists('link_member_proposals')) {
      return 'link_member_proposals';
    }
    return 'partner_proposals';
  }

  Future<bool> _tableExists(String table) async {
    final rows = await customSelect(
      "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
      variables: [Variable.withString(table)],
    ).get();
    return rows.isNotEmpty;
  }

  Future<bool> _columnExists(String table, String column) async {
    final rows = await customSelect('PRAGMA table_info($table)').get();
    return rows.any((row) => row.read<String>('name') == column);
  }

  /// Encrypted on-disk SQLite (SQLite3MultipleCiphers) in documents.
  static QueryExecutor _openConnection() {
    return openEncryptedDatabase(
      name: 'kinetic_link',
      databaseDirectory: getApplicationDocumentsDirectory,
    );
  }
}
